% helper functions for implementing ALPC-SFS
% Lei Wang, ieeewangl@gmail.com
% Sept. 28, 2020 @Radboud Uni.

function Utils3 = Utils3
    
    Utils3.createFit_sigmoid_tau = @createFit_sigmoid_tau;
    Utils3.createFit_sigmoid_norm = @createFit_sigmoid_norm;
end



function [fitresult, gof] = createFit_sigmoid_tau(X, tau_1)
%CREATEFIT(X,TAU_1)
%  Create a fit.
%
%  Data for 'norm_sigmoid_fit_tau' fit:
%      X Input : X
%      Y Output: tau_1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Jan-2020 17:07:58


%% Fit: 'norm_sigmoid_fit_tau'.
[xData, yData] = prepareCurveData( X, tau_1 );

% Set up fittype and options.
ft = fittype( 'a/(1+exp(-b*x))+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.109507928198957 0.681726862398947 0.147744338942165];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'norm_sigmoid_fit_tau' );
% h = plot( fitresult, xData, yData );
% legend( h, 'tau_1 vs. X', 'sigmoid fit line', 'Location', 'NorthEast' );
% % Label axes
% xlabel X
% ylabel tau_1
% grid on

end


function [fitresult, gof] = createFit_sigmoid_norm(X, Y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'norm_sigmoid_fit_tau' fit:
%      X Input : X
%      Y Output: Y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Jan-2020 16:53:58


%% Fit: 'norm_sigmoid_fit_tau'.
[xData, yData] = prepareCurveData( X, Y );

% Set up fittype and options.
ft = fittype( 'a/(1+exp(-b*x))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.226834667587911 0.218934669884514];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'norm_sigmoid_fit_tau' );
h = plot( fitresult, xData, yData );
legend( h, 'real data', 'sigmoid fit line', 'Location', 'NorthEast' );
% Label axes
xlabel X
ylabel Y
grid on

end

